services:
  generator:
    image: ghcr.io/adomi-io/contract-builder-openapi:latest
    environment:
      - GENERATORS=python,typescript-axios,graphql-schema
      - GENERATOR_PYTHON_ADDITIONAL_PROPERTIES=identifierNamingConvention=snake_case,useSingleRequestParameter=true
      - GENERATOR_GRAPHQL_SCHEMA_ADDITIONAL_PROPERTIES=withInterfaces=true
    volumes:
      # Mount the specs directory from the docker folder
      - ./specs:/local/src:ro
      # Mount an output directory relative to this docker-compose file
      - ./out:/local/out
